/** PARTIE DESIGN UI & FULLSTACK VISIBLE AU DEMARRAGE */
const toolsDatas = [
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Adobe Color',
    description:
      'Roue chromatique & Palettes de couleurs, Thèmes et Tendances, Bibliothèque...',
    webSite: 'https://color.adobe.com/fr/create/color-wheel',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Colorable',
    description:
      'Accessibilité des couleurs, contraste, luminosité. Reverse/Random.',
    webSite: 'https://colorable.jxnblk.com/87e395/751967',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Coolors',
    description:
      'Roue chromatique & Palettes de couleurs, Thèmes et Tendances, Bibliothèque...',
    webSite: 'https://coolors.co/palettes/trending',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Flat UI Colors',
    description: 'Palettes de couleurs, couleurs réseaux sociaux, Colo Picker.',
    webSite: 'https://www.materialui.co/flatuicolors',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Flat UI ColorPicker',
    description:
      'Palettes de couleurs, Modèles de couleurs HEX, RGBA, HSL, HSLA...',
    webSite: 'http://www.flatuicolorpicker.com/',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'Tanaguru Contrast Finder',
    description:
      "Trouver les bons contrastes entre 2 couleurs pour l'accessibilité WebAssembly.",
    webSite: 'https://contrast-finder.tanaguru.com/',
    textColors: '#d4e038',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Carbon',
    description: 'Créer et partager de belles images de son code source.',
    webSite: 'https://carbon.now.sh/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Codelf',
    description:
      'Aide au nommage de variables. Recherche sur Github, GitLab et Bitbucket pour voir si ton idée de nom est populaire.',
    webSite: 'https://unbug.github.io/codelf/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'CodeSandbox',
    description:
      'Editeur de code en ligne, IDE rapide à utiliser et collaboratif.',
    webSite: 'https://codesandbox.io/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'CyberChef',
    description:
      "Multitude d'outils pour devs. RegEx, URL Decode, JSON to CSV, CSV to JSON, public Key, utils, Reverse, Sort, Filter, Split, random générator, Date/Time...",
    webSite: 'https://coolors.co/palettes/trending',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'ExcaliDraw',
    description:
      "Tableau blanc qui permet de facilement dessiner un plan comme si c'était fait à la main. Une page blanche pour faire des shchémas et les enregistrer. Simple et gratuit.",
    webSite: 'https://excalidraw.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Photopea',
    description:
      "Photoshop gratuit dans le navigateur. permet de faire des retouches d'images, des conversion de formats...",
    webSite: 'https://www.photopea.com/',
    textColors: '',
    emoji: '',
  },
]

/** PARTIE DESIGN UI VISIBLE AU CLIC SUR SHOW MORE */
const toolsDatasMore = [
  {
    level: 'Design UI',
    category: 'Couleurs',
    nameSite: 'WebAIM',
    description:
      'Accessibilité des couleurs, vérificateur de contraste (Contrast ratio).',
    webSite: 'https://webaim.org/resources/contrastchecker/',
    textColors: '#d4e038',
    emoji: '',
  },
  // BACKGROUND
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Ambient Canvas Backgrounds',
    description: 'Générateur de gradients avec Animation possible. Copy CSS.',
    webSite:
      'https://tympanus.net/Development/AmbientCanvasBackgrounds/index5.html',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Gradient Animator',
    description:
      '5 BG API HTML 5 Canvas : Pipeline, Aurora, Swirl, Shift et Coalesce.',
    webSite: 'https://www.gradient-animator.com/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Gradient Magic',
    description: 'Palettes de couleurs, générateurs de gradient...',
    webSite: 'https://www.gradientmagic.com/collection/popular',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Hero Patterns',
    description: 'Collection de Background SVG. Copy CSS & export SVG.',
    webSite: 'https://heropatterns.com/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Magic Pattern',
    description:
      'FREE : CSS Patterns, Générateur Gradients et de Blob, Doodle background.',
    webSite: 'https://www.magicpattern.design/tools/css-backgrounds',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Pattern Monster',
    description:
      'Collection de Background SVG. Un générateur pour créer des motifs SVG. Copy CSS, SVG. Export SVG, PNG.',
    webSite: 'https://fr.pattern.monster/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Subtle Patterns',
    description: 'Collection de Background Textures. Images PNG.',
    webSite: 'https://www.toptal.com/designers/subtlepatterns/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'SVG Backgrounds',
    description: 'Jolis Backgrounds. Copy CSS, Inline SVG ou export SVG.',
    webSite: 'https://www.svgbackgrounds.com/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Thpace',
    description: 'Background animé avec API HTML 5 Canvas.',
    webSite: 'https://www.braedin.com/Thpace/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'The Pattern Library',
    description: 'Backgrounds images originaux (JPG, PNG, GIF).',
    webSite: 'http://thepatternlibrary.com/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Tympanus',
    description:
      'Démos sympas de backgrounds animés, avec effets Push, Fade Out, Grid, Slice, Side...',
    webSite: 'https://tympanus.net/Development/ArticleIntroEffects/index.html',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'UI Gradients',
    description: 'Générateur de gradients. Copy CSS & export image .jpg',
    webSite: 'https://coolors.co/palettes/trending',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Vanta.js',
    description:
      "Backgrounds animés. Personnalisation possible et utilisation d'un CDN.",
    webSite: 'https://www.vantajs.com/',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Websites For Creative BG',
    description: 'Propose plusieurs sites de création de backgrounds.',
    webSite: 'https://dev.to/vincenius/websites-for-creative-backgrounds-1mao',
    textColors: '#3195ff',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Background',
    nameSite: 'Wweb.dev',
    description: '3 démo backgrounds animés. Copy HTML & CSS.',
    webSite: 'https://wweb.dev/resources/animated-css-background-generator/',
    textColors: '#3195ff',
    emoji: '',
  },
  // IMG & ICONS
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Creative Ressources',
    description:
      '221 ressources, 15 catégories: icônes, img, illustrations, webdesign, colors, background, fonts, outils divers...',
    webSite: 'https://creative-ressources.fr/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Emojipedia',
    description: "Ressources d'emojis.",
    webSite: 'https://emojipedia.org/',
    textColors: '#e06f21',
    emoji: '👾',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'EmojiTerra',
    description: "Listes d'emojis, recherche par catégories. Langue FR.",
    webSite: 'https://emojiterra.com/fr/',
    textColors: '#e06f21',
    emoji: '🦜',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Favicon-Generator',
    description: 'Générateur de favicon.io',
    webSite: 'https://www.favicon-generator.org/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Real Favicon Generator',
    description: 'Générateur de favicon.io',
    webSite: 'https://realfavicongenerator.net/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Flat Icon',
    description:
      "Télécharger des icônes ou pack d'icônes (PNG, SVG, EPS, PSD).",
    webSite: 'https://www.flaticon.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'FontAwesome',
    description:
      "Ressources d'icônes. Possibilité d'utiliser un CDN (cdnjs.com).",
    webSite: 'https://fontawesome.com/v5.15/icons?d=gallery&p=2',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Freepik',
    description:
      "Ressources d'images : Vecteurs, Photos de Stock et PSD gratuites.",
    webSite: 'https://fr.freepik.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Giphy',
    description: "Ressources d'images au format GIF et stickers.",
    webSite: 'https://giphy.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Icon-Icons',
    description: 'Icônes gratuites (SVG - PNG).',
    webSite: 'https://icon-icons.com/fr/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Icones8',
    description:
      'Icônes, illustrations, photos, musique et outils de design. Services API Icônes, Photos, Musique, Vecteurs.',
    webSite: 'https://icones8.fr/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Ionicons',
    description: "Ressources d'icônes open source.",
    webSite: 'https://ionic.io/ionicons',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Lorem Flickr',
    description:
      "Fournit des images aléatoires. Tag 'img' a insérer dans le code HTML..",
    webSite: 'https://loremflickr.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Lorem Picsum',
    description:
      'Images aléatoires. Changer la taille, obtenir une image carrée, une img spécifique, img aléatoire statique, noir&blanc, floue...',
    webSite: 'https://picsum.photos/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Pexels',
    description: "Ressources d'images gratuites.",
    webSite: 'https://www.pexels.com/fr-fr/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Pikwizard',
    description: 'Ressources de photos et vidéos gratuites.',
    webSite: 'https://pikwizard.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Pixabay',
    description: 'Images libres de droits & gratuites à télécharger.',
    webSite: 'https://pixabay.com/fr/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Remove.bg',
    description: "Outil permettant de supprimer l'arrière-plan d'une image.",
    webSite: 'https://www.remove.bg/fr',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Reshot',
    description: "Ressources d'icônes, illustrations et photos.",
    webSite: 'https://www.reshot.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Rocket Emoji',
    description: 'Copier/Coller des emojis.',
    webSite: 'https://rocketemoji.co/',
    textColors: '#e06f21',
    emoji: '🚀',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Sqoosh',
    description: "Outil permettant de réduire le poids d'une image.",
    webSite: 'https://squoosh.app/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Stickpng',
    description: "Ressources d'images PNG avec fond transparent.",
    webSite: 'https://www.stickpng.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Undraw',
    description:
      'Illustrations open source. Images SVG. Possibilité de changer les couleurs dans les SVG.',
    webSite: 'https://undraw.co/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Unsplash',
    description: "Ressources d'images gratuites.",
    webSite: 'https://unsplash.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Unsplash Random',
    description:
      'Unsplash API pour générer des images : Photos de profils, Users...',
    webSite: 'https://unsplash.com/developers',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'Vexels',
    description:
      'Ressources graphiques : dessins vectoriels, SVG, PNG, maquettes PSD.',
    webSite: 'https://www.vexels.com/',
    textColors: '#e06f21',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Img & Icons',
    nameSite: 'wpRock',
    description: 'Copier/Coller des emojis. Langue FR.',
    webSite: 'https://wprock.fr/t/emoji/',
    textColors: '#e06f21',
    emoji: '🏳️‍🌈',
  },
  // VIDEOS
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Compressvideo',
    description:
      'Réduire la taille des vidéos directement depuis votre navigateur Web, sans installer aucune application.',
    webSite: 'https://www.compresservideo.fr/',
    textColors: '#3bf06b',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Cover',
    description:
      'Collections de vidéos payantes et gratuites. A venir : musiques gratuites.',
    webSite: 'https://coverr.co/',
    textColors: '#3bf06b',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Life of vids',
    description: 'Collections de vidéos gratuites.',
    webSite: 'https://www.lifeofvids.com/',
    textColors: '#3bf06b',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Mazwai',
    description: 'Collection de clips video gratuits.',
    webSite: 'https://mazwai.com/',
    textColors: '#3bf06b',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Pexels Vidéos',
    description: 'Collection de videos gratuites.',
    webSite: 'https://www.pexels.com/videos/',
    textColors: '#3bf06b',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Vidéos',
    nameSite: 'Videvo',
    description: 'Collection de videos gratuites.',
    webSite: 'https://www.videvo.net/',
    textColors: '#3bf06b',
    emoji: '',
  },
  // TYPOGRAPHIE
  {
    level: 'Design UI',
    category: 'Typographie',
    nameSite: 'Creative Bloq',
    description:
      'Blog sur le graphic design, web design, tendances. Les meilleures paires de police pour une typo harmonieuse.',
    webSite:
      'https://www.creativebloq.com/typography/20-perfect-type-pairings-3132120',
    textColors: '#db59fa',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Typographie',
    nameSite: 'FontJoy',
    description: 'Générateur de paires de police.',
    webSite: 'https://fontjoy.com/',
    textColors: '#db59fa',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'Typographie',
    nameSite: 'Google Fonts',
    description: 'Collections de polices faciles à intégrer.',
    webSite:
      'https://fonts.google.com/?preview.text=&preview.text_type=custom&sidebar.open=true',
    textColors: '#db59fa',
    emoji: '',
  },
  // WEBDESIGN
  {
    level: 'Design UI',
    category: 'WebDesign',
    nameSite: 'Awwwards',
    description: 'Ressources sur le WebDesign.',
    webSite: 'https://www.awwwards.com/',
    textColors: '#9e875d',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'WebDesign',
    nameSite: 'Behance',
    description: 'Ressources sur le WebDesign.',
    webSite: 'https://www.behance.net/',
    textColors: '#9e875d',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'WebDesign',
    nameSite: 'Brutalist Websites',
    description: 'Ressources sur la tendance "Brutalisme".',
    webSite: 'https://brutalistwebsites.com/',
    textColors: '#9e875d',
    emoji: '',
  },
  {
    level: 'Design UI',
    category: 'WebDesign',
    nameSite: 'Dribbble',
    description: 'Ressources sur le WebDesign.',
    webSite: 'https://dribbble.com/',
    textColors: '#9e875d',
    emoji: '',
  },
]

/** PARTIE FULLSTACK VISIBLE AU CLIC SUR SHOW MORE */
const toolsDatasFullMore = [
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'DevDocs API',
    description:
      'Documentation de tous les frameworks/langages dans un seul endroit bien organisé....',
    webSite: 'https://devdocs.io/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'DevHints',
    description:
      'Aide-mémoire de bouts de code, syntaxes, snippets pour tous les langages et frameworks.',
    webSite: 'https://devhints.io/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'ExplainShell',
    description:
      "Permet de retrouver les petites options de tous les commandes shell. Copier/Coller n'importe quelle commande et d'avoir une explication.",
    webSite: 'https://explainshell.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Hoppscotch',
    description:
      'Comme POSTMAN mais directement dans le navigateur. Peut dépanner pour tester rapidement une API.',
    webSite: 'https://hoppscotch.io/fr/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Htaccess Tester',
    description:
      "Permet de connaître le comportement de ton htaccess avant de le  pousser. Ton site n'implosera pas et les redirections seront correctes.",
    webSite: 'https://htaccess.madewithlove.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'html-css-js cheatsheet',
    description:
      "Outils HTML, CSS et JS. Trouver les codes HTML des emojis. Aide-Mémoire (CheatSheet), Editor. Générateur d'images, iframe, tableaux, listes...",
    webSite: 'https://htmlcheatsheet.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Internet Speed Test',
    description: 'Mesure les performances de ton réseau.',
    webSite: 'https://speed.cloudflare.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Je suis un dev',
    description:
      "Blog d'un dev. Article sur les 20 outils webs ndispensables pour développeurs.",
    webSite: 'https://www.jesuisundev.com/20-outils-webs/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'JSON Editor Online',
    description:
      "Permet de créer ou télécharger un document en JSON, de le visualiser, de l'enregistrer et de le partager.",
    webSite: 'https://jsoneditoronline.org/#right=local.sisohu',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Learn X in Y minutes',
    description:
      'Tous les langages possibles, expliqués en une page, dans presque toutes les langues, via des exemples concrets de code.',
    webSite: 'https://learnxinyminutes.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Markdown Daring Fireball',
    description:
      'Obtenir la syntaxe du Markdown. Documentation complète et possibilité de le traduire en HTML.',
    webSite: 'https://daringfireball.net/projects/markdown/basics',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Mockaroo',
    description:
      "Permet de générer jusqu'à 1000 lignes de données fictives de test réalistes aux formats CSV, JSON, SQL et Excel.",
    webSite: 'https://www.mockaroo.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Neumorphism',
    description:
      'Générateur CSS de formes concernant la tendance "Néomorphisme".',
    webSite: 'https://neumorphism.io/#d3caca',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Regex01',
    description:
      'Permet de créer, modifier une regex. Tous les tests sont fait instantanément à chaque modification. Pour en décoder une, je copie/colle et j’ai toute l’explication.',
    webSite: 'https://regex101.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Replit',
    description:
      'IDE en ligne pour front&back (Node, Python, Java, PHP, JS...). Prototyper des bouts de code backends rapidement. Valider une fonction, un bout d’algo ...',
    webSite: 'https://replit.com/',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Rosetta Code',
    description:
      "Permet de retrouver l'implémentation de tel algo dans tel langage.",
    webSite: 'http://www.rosettacode.org/wiki/Rosetta_Code',
    textColors: '',
    emoji: '',
  },
  {
    level: 'Fullstack',
    category: '💻',
    nameSite: 'Snippet Generator',
    description:
      "Permet de générer des snippets. On copie son code et ça retranscrit le snippet sur l'IDE choisit (VSCode, Atom, Sublime text).",
    webSite:
      'https://snippet-generator.app/?description=&tabtrigger=&snippet=&mode=vscode',
    textColors: '',
    emoji: '',
  },
]
